name: SQTrade2
main: nickmiste.SQTrade2
version: 1.0
commands:
   buy:
      description: Used when buying from a dropper shop
      usage: /buy <amount>
permissions:
   sqtrade.breakshops:
      description: Allows staff to break shops made by other players
      default: op      