# Speed is measured in how long it takes for a block to break
# in ticks.
default speed: 20
energy consumption per block: 50
testing version: false

fuel:
  coal:
    energy per tick: 2
    burn time: 500