# Speed is measured in how long it takes for a block to break
# in ticks.
normal speed: 20
fast speed: 10
energy consumption per block: 50
testing version: false

fuel:
  coal:
    energy per tick: 2
    burn time: 500