name: More-Mobs
main: com.dibujaron.MoreMobs.MoreMobs
version: 1.7.3
dev-url: http://dev.bukkit.org/server-mods/more-mobs/
commands:
   alliance:
      description: The alliance command
      usage: /alliance help
   a:
      description: The alliance command
      usage: /alliance help
