name: SQBlasters
main: com.ginger_walnut.sqblasters.Main
version: 1.1.1
description: A plugin that changes bows to blasters
commands:
  blaster:
    description: Manages SQBlasters
  blaster help:
    description: Displays help for SQBlasters
  blaster create:
    description: Creates a new blaster
  blaster recipie:
    description: Displays the recipies for blasters
  blaster guide:
    description: Displays the guide for SQBlasters