name: SQExpBoost
main: com.ginger_walnut.sqexpboost.Main
version: 1.0
description: A plugin that adds the ability to boost exp drops.
commands:
   expboost:
      description: Manages ExpBoost
   expboost help:
      description: Shows the help for ExpBoost
   expboost set:
      description: Sets the base exp multiplier
   expboost timeboost:
      description: Manages time based exp multipliers
   expboost timeboost set:
      description: Sets a time based exp multiplier
permissions:
   SQExpBoost.viewHelp:
      description: Premission node for viewing help
      default: false
   SQExpBoost.setMultiplier:
      description: Premission node for setting multiplier
      default: false
   SQExpBoost.addMultiplier:
      description: Premission node for adding to the multiplier
      default: false
   SQExpBoost.subtractMultiplier:
      description: Premission node for subtracting to the multiplier
      default: false