name: SQPlanet
main: com.burkentertainment.SQPlanet.SQPlanetPlugin
version: 1.6.0
commands:
  SQPlanet:
     description: Control and edit spawning planet customization rules
     usage: /SQPlanet reload
     permission: sqplanet.admin
     permission-message: Missing permissions to edit SQPlanet settings
permissions:
  sqplanet.admin:
    description: Allows administrative access to SQPlanet
    default: op
    