weapons:
  cannon:
    damage: 10
    carry over: false
    material: PISTON_BASE
    cooldown: 0
    explosive mode cooldown: 50
    explosion power: 1

  missile launcher:
    damage: 200
    carry over: true
    material: DISPENSER
    cooldown: 60
    explosion power: 2
    
  heatseeking missile:
    detection range: 100
    cooldown: 5
    fuelTime: 30
    damage: 500
    carry over: true

utilites:
  reactor:
    material: DROPPER
    fuel per coal: 100
    fuel per second: 5
    catalyst: EYE_OF_ENDER
  emFieldGenerator:
    material: GOLD_BLOCK
    fieldPower: 1000.0
blocks:
  wool:
    material: WOOL
    hp: 30
    weight: 1
  glass:
    material: GLASS
    hp: 20
    weight: 1
  coal:
    material: PISTON_BASE
    hp: 50
    weight: 20
  dispenser:
    material: DISPENSER
    hp: 50
    weight: 20
  reactor:
    material: DROPPER
    hp: 30
    weight: 1
  emFieldGenerator:
    material: GOLD_BLOCK
    hp: 1
    weight: 20
  diamond:
    material: DIAMOND_BLOCK
    hp: 200
    weight: 20
  iron:
    material: IRON_BLOCK
    hp: 120
    weight: 10
  clay:
    material: STAINED_CLAY
    hp: 70
    weight: 5
  sea_Lantern:
    material: SEA_LANTERN
    hp: 20
    weight: 1