name: SQSmoothCraft
main: com.ginger_walnut.sqsmoothcraft.SQSmoothCraft
version: 0.0.1
description: A plugin that adds smooth space ships
depend: [ProtocolLib]
commands:
  ship:
    description: spawns a default ship
  shipdetect:
    description: detects a ship
  shipundetect:
    description: undetects a ship
  ship3rdperson:
    description: puts a ship in 3rd person mode