regions:
  region1:
    owner: Arator
    capture points:
      point1:
        position: 8,100,8
        owner: Arator
      point2:
        position: 7,70,7
        owner: Yavari
      point3:
        owner: None
        position: 7,90,8
    connections:
    - region2
    points:
    - 100,100
    - 100,200
    - 150,100
