name: SQTechBase
version: 1.0
description: Technology plugin for minecraft
main: com.starquestminecraft.sqtechbase.SQTechBase
softdepend: [Movecraft]
commands:
   sqtech:
     description: Manages SQTech