name: SQTechPumps
main: com.martinjonsson01.sqtechpumps.SQTechPumps
version: 1.1.7
description: Pumps that pump liquids and tanks that store liquids!
depend: [SQTechBase]
commands:
      
permissions: