#available currencies are:
#reputation (good-guy kills)
#infamy (black market kills)
#philanthropy (charity)
#merchanting (good-guy trading)
#smuggling (black market trading)
#salvage (implement later)
stations:
    - Regalis_West_Station
    - Regalis_North_Station
    - Defalos_West_Station
    - Defalos_East_Station
    - Digitalia_South_Station
    - Digitalia_East_Station
contracts:
    itemWoolExample:
        type: item
        minReward: 5000
        maxReward: 10000
        minLevels:
            merchanting: 0
            philanthropy: 0
        blackMarket: false
        items:
            whitewool:
                type: WOOL
                data: 0
                minAmount: 1000
                maxAmount: 2000
            bluewool:
                type: WOOL
                data: 11
                minAmount: 500
                maxAmount: 1000
            redwool:
                type: WOOL
                data: 14
                minAmount: 500
                maxAmount: 1000
    smuggleWoodExample:
        type: item
        minReward: 10000
        maxReward: 15000
        minLevels:
            smuggling: 0
        blackMarket: true
        items:
            birchwood:
                type: LOG
                data: 2
                minAmount: 750
                maxAmount: 1000
            oakwood:
                type: LOG
                data: 0
                minAmount: 100
                maxAmount: 200
    reputationExample:
        type: capture
        minReward: 5000
        maxReward: 10000
        minLevels:
            reputation: 0
        blackMarket: false
        targetClasses:
            - BlockadeRunner
            - Gunship
            - Starfighter
        minAmount: 2
        maxAmount: 4
    piracyExample:
        type: capture
        minReward: 10000
        maxReward: 20000
        minLevels:
            infamy: 5
        blackMarket: true
        targetClasses:
            - HeavyFreighter
            - LightFreighter
            - SuperFreighter
            - Starfighter
        minAmount: 5
        maxAmount: 10
    philanthropyExample:
        type: money
        minLevels:
            philanthropy: 0
        cost: 100000
        cause: "Starving orphan children on Kelakaria"
            
            
                