name: SQContracts
version: 3.1.32
description: Contracts for your goods!
author: dibujaron
website: http://starquestminecraft.com
main: com.starquestminecraft.sqcontracts.SQContracts
depend:
    - Movecraft

commands:
   contract:
      description: contract master command.
      usage: /contract