name: SQMobDropBoost
main: com.ginger_walnut.sqmobdropboost.Main
version: 1.0
description: A plugin that adds the ability to boost mob drops.
commands:
   mobdropboost:
      description: Manages SQMobDropBoost
   mobdropboost help:
      description: Shows the help for SQMobDropBoost
   mobdropboost set:
      description: Sets the base mob drop multiplier
permissions:
   SQMobDropBoost.viewHelp:
      description: Premission node for viewing help
      default: false
   SQMobDropBoost.setMultiplier:
      description: Premission node for setting the multiplier
      default: false
   SQMobDropBoost.addMultiplier:
      description: Premission node for adding to the multiplier
      default: false
   SQMobDropBoost.subtractMultiplier:
      description: Premission node for subtracting to the multiplier
      default: false