name: SQRankup
main: com.regalphoenixmc.SQRankup.SQRankup
version: 1.7.3
softdepend: [PermissionsEx]
depend: [Vault]
commands:
  rankup:
    description: Rank up!
    usage: /rankup
  addapp:
    description: Mark a player as applied.
    usage: /addapp <Player>
  rankuppurchase:
  rankupTransfer:
   