name: SQRankup
main: com.regalphoenixmc.SQRankup.SQRankup
version: 1.7.3
depend: [PermissionsEx]
commands:
  rankup:
    description: Rank up!
    usage: /rankup
  addapp:
    description: Mark a player as applied.
    usage: /addapp <Player>
  migrate:
    description: Be jewish
    usage: Suck many jews
   