name: SQApocalypse
main: com.dibujaron.sqapocalypse.SQApocalypse
version: 1.0.0
commands:
  apocalypse:
    description: apocalypse information.
    usage: /apoc score or /apoc top
    aliases: [apoc, sqapocalypse]
depend: [Movecraft]