name: SQSmoothCraft2
main: me.ginger_walnut.sqsmoothcraft.SQSmoothCraft
version: 0.0.1
description: A plugin that adds smooth space ships
depend: [ProtocolLib]
commands:
  ship:
    description: main command for SQSmoothCraft
permissions:
  SQSmoothCraft.spawnShip:
    description: Permission node for spawning a default smoothcraft ship