connections:
  connection1:
    region 1: region1
    region 2: region2
    x1: 0
    z1: 0
    x2: 100
    z2: 100
regions:
  region1:
    owner: Arator
    capture points:
       point1:
         position: 8,100,8
         owner: Arator
       point2:
         position: 7,70,7
         owner: Yavari
    points:
    - 100,100
    - 100,200
    - 150,100