name: SQDuties
main: com.ginger_walnut.sqduties.SQDuties
version: 2.1
description: A plugin that allows mods to go into duty mode
commands:
   duty:
      description: toggles duty mode
   invrestore:
      description: restores inventory