mainServers:
  - Limbo
  - waitroom
  - Defalos
  - Drakos
  - Emera
  - Krystallos
  - Acualis
  - Regalis
  - Quavara
  - Boskevine
  - Kelakaria
  - Boletarian
  - Digitalia
  - Valadro
  - Ceharram
  - Iffrizar
  - AsteroidBelt
  - Inaris